version: 2.1


jobs:
  print_hello:
  docker:
    - image: circleci/node:13.8.0
  print_world:
  docker:
    - image: circleci/node:13.8.0

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
